In [1]:
import numpy as np

In [ ]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


##Mi Ejemplo

In [2]:
lista_precios = [20.43, 75.83, 142.68, 154.02, 5253.5, 142.62]
arreglo_precios = np.array(lista_precios)
print(arreglo_precios, type(arreglo_precios))

[  20.43   75.83  142.68  154.02 5253.5   142.62] <class 'numpy.ndarray'>


In [ ]:
Ar = np.array([[1,3],[2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


##Mi Ejemplo

In [5]:
Arreglo = np.array([[8,7],[6,5],[2,66]])
print(Arreglo, type(Arreglo))

[[ 8  7]
 [ 6  5]
 [ 2 66]] <class 'numpy.ndarray'>


In [ ]:
print(Ar.shape)

(2, 2)


##Mi Ejemplo

In [6]:
print(Arreglo.shape)

(3, 2)


In [ ]:
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


##Mi Ejemplo

In [7]:
print(Arreglo[0])
print(Arreglo[1])

[8 7]
[6 5]


In [ ]:
print('the first column: ', Ar[:,0])
print('the second column: ', Ar[:,1])

the first column:  [1 2]
the second column:  [3 4]


##Mi Ejemplo

In [10]:
print('La primera columna: ', Arreglo[:,0])
print('La segunda columna: ', Arreglo[:,1])

La primera columna:  [8 6 2]
La segunda columna:  [ 7  5 66]


In [ ]:
print(np.log(price_array))

[ 4.96793654  4.98244156  4.9675886   4.96995218  4.96633504  4.96018375]


##Mi Ejemplo

In [11]:
print(np.log(arreglo_precios))

[3.01700441 4.32849399 4.96060436 5.03708246 8.5666498  4.96018375]


In [ ]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

143.89666666666668
0.9673790478515796
863.38
145.83


##Mi Ejemplo

In [12]:
print(np.mean(arreglo_precios))
print(np.std(arreglo_precios))
print(np.sum(arreglo_precios))
print(np.max(arreglo_precios))

964.8466666666667
1918.5183297679373
5789.08
5253.5


In [13]:
import pandas as pd

In [ ]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
s

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64

##Mi Ejemplo

In [15]:
precios = [9983.2, 563.4, 143.68, 144.02, 633.5, 142.62]
serie = pd.Series(precios)
serie

0    9983.20
1     563.40
2     143.68
3     144.02
4     633.50
5     142.62
dtype: float64

In [ ]:
s = pd.Series(price,index = ['a','b','c','d','e','f'])
s

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64

##Mi Ejemplo

In [16]:
s = pd.Series(precios,index = ['lapiz','papel','corbata','borrador','boligrafo','marcador'])
s

lapiz        9983.20
papel         563.40
corbata       143.68
borrador      144.02
boligrafo     633.50
marcador      142.62
dtype: float64

In [ ]:
s.index = [6,5,4,3,2,1]
s

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64

##Mi Ejemplo

In [17]:
s.index = [7,8,9,10,11,12]
s

7     9983.20
8      563.40
9      143.68
10     144.02
11     633.50
12     142.62
dtype: float64

In [ ]:
print(s[1:])
print(s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


##Mi Ejemplo

In [22]:
print(s[2:])
print(s[:-1])

9     143.68
10    144.02
11    633.50
12    142.62
dtype: float64
7     9983.20
8      563.40
9      143.68
10     144.02
11     633.50
dtype: float64


In [ ]:
print(s[4])
s[4] = 0
print(s)

##Mi Ejemplo

In [ ]:
print(s[0])
s[3] = 10
print(s)

In [ ]:
s = pd.Series(price, name = 'Apple Price List')
print(s)
print(s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Price List, dtype: float64
Apple Price List


##Mi Ejemplo

In [26]:
s = pd.Series(precios, name = 'Lista de Precios:')
print(s)
print(s.name)

0    9983.20
1     563.40
2     143.68
3     144.02
4     633.50
5     142.62
Name: Lista de Precios:, dtype: float64
Lista de Precios:


In [ ]:
time_index = pd.date_range('2017-01-01',periods = len(s),freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Price List, dtype: float64


##Mi Ejemplo

In [27]:
time_index = pd.date_range('2018-01-01',periods = len(s),freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06'],
              dtype='datetime64[ns]', freq='D')
2018-01-01    9983.20
2018-01-02     563.40
2018-01-03     143.68
2018-01-04     144.02
2018-01-05     633.50
2018-01-06     142.62
Freq: D, Name: Lista de Precios:, dtype: float64


In [ ]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Price List, dtype: float64
142.62


In [ ]:
print(s.iloc[1])

145.83


##Mi Ejemplo

In [28]:
s.index = [10,20,30,40,50,60]
print(s)
print(s[3])

10    9983.20
20     563.40
30     143.68
40     144.02
50     633.50
60     142.62
Name: Lista de Precios:, dtype: float64


KeyError: ignored

In [ ]:
s.index = time_index
print(s['2017-01-03'])

143.68


##Mi Ejemplo

In [29]:
s.index = time_index
print(s['2018-01-03'])

143.68


In [ ]:
print(s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Price List, dtype: float64


##Mi Ejemplo

In [32]:
print(s['2018-01-02':'2018-01-05'])

2018-01-02    563.40
2018-01-03    143.68
2018-01-04    144.02
2018-01-05    633.50
Freq: D, Name: Lista de Precios:, dtype: float64


In [ ]:
print(s[s < np.mean(s)] )
print([(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

6    143.73
4    143.68
2    143.50
1    142.62
Name: Apple Price List, dtype: float64
[6    False
5    False
4    False
3     True
2    False
1    False
Name: Apple Price List, dtype: bool]


##Mi Ejemplo

In [33]:
print(s[s < np.mean(s)] )
print([(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2018-01-02    563.40
2018-01-03    143.68
2018-01-04    144.02
2018-01-05    633.50
2018-01-06    142.62
Freq: D, Name: Lista de Precios:, dtype: float64
[2018-01-01    False
2018-01-02    False
2018-01-03    False
2018-01-04    False
2018-01-05    False
2018-01-06    False
Freq: D, Name: Lista de Precios:, dtype: bool]
